from flask import render_template, flash, redirect
from app import app
import pymysql
from database import temp #sensor readings
from database import db_connect
from database import db_insert_into_table
from database import db_students
#connect to sensors

#connect to database
db_connect.sqlconnector()
'''

sql = """INSERT INTO JIVELY
            (NAME, HUMIDITY, TEMPERATURE)
   VALUES ('Niv', 20, 30)""" #change to values generated by temp.py
try:
   # Execute the SQL command
   cursor.execute(sql)
   # Commit your changes in the database
   db.commit()
except:
   # Rollback in case there is any error
   db.rollback()

# disconnect from server
db.close()'''

from app.forms import LoginForm
#from database import db_connect #gets the connection in place
@app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        #database insert

        flash('Login requested for user {}, remember_me={}'.format(
            form.username.data, form.remember_me.data))
        '''# Open database connection
        db = pymysql.connect("localhost","testuser","test123","TESTDB" )

        # prepare a cursor object using cursor() method
        cursor = db.cursor()

        # Prepare SQL query to INSERT a record into the database.
        sql = """INSERT INTO JIVELY
            (NAME, HUMIDITY, TEMPERATURE)
        VALUES (username, 20, 30)""" #change to values generated by temp.py
        '''

        #insert into table, values
        #db_insert_into_table.sqlinsert()
        db_students.sql_insert()

        return redirect('/index')
    return render_template('login.html', title='Sign In', form=form)

@app.route('/')
@app.route('/index')
def index():
	user = {'username': 'Andy'}
	posts = [
	        {
        	    'author': {'username': 'John'},
        	    'body': 'Beautiful day in Portland!'
        	},
       		{
        	    'author': {'username': 'Susan'},
        	    'body': 'The Avengers movie was so cool!'
        	}
	]
	return render_template('index.html', title='Home', user=user, posts=posts)
