#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 19 03:12:24 2018

@author: niveditanatarajan
"""
import pymysql
import sqlalchemy
import pyodbc
#!/usr/bin/python3
'''
import pymysql

# Open database connection
db = pymysql.connect("localhost","testuser","test123","TESTDB" )

# prepare a cursor object using cursor() method
cursor = db.cursor()

# Prepare SQL query to INSERT a record into the database.
sql = """INSERT INTO JIVELY
            (NAME, HUMIDITY, TEMPERATURE)
   VALUES ('Niv', 20, 30)""" #change to values generated by temp.py
try:
   # Execute the SQL command
   cursor.execute(sql)
   # Commit your changes in the database
   db.commit()
except:
   # Rollback in case there is any error
   db.rollback()

# disconnect from server
db.close()
'''
def sqlinsert():
    db=pymysql.connect("localhost","testuser","test123","TESTDB")
    cursor=db.cursor()
    sql = """INSERT INTO JIVELY
        (NAME,HUMIDITY,TEMPERATURE)
        VALUES ('Niv',20,30)"""
    try:
        cursor.execute(sql)
        db.commit()
    except:
        db.rollback()
    db.close()